// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/contracts/rooms.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomsManagerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomsManagerConfig) Reset() {
	*x = RoomsManagerConfig{}
	mi := &file_internal_contracts_rooms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomsManagerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomsManagerConfig) ProtoMessage() {}

func (x *RoomsManagerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_rooms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomsManagerConfig.ProtoReflect.Descriptor instead.
func (*RoomsManagerConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_rooms_proto_rawDescGZIP(), []int{0}
}

type RoomJoinConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomJoinConfig) Reset() {
	*x = RoomJoinConfig{}
	mi := &file_internal_contracts_rooms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomJoinConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomJoinConfig) ProtoMessage() {}

func (x *RoomJoinConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_rooms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomJoinConfig.ProtoReflect.Descriptor instead.
func (*RoomJoinConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_rooms_proto_rawDescGZIP(), []int{1}
}

func (x *RoomJoinConfig) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *RoomJoinConfig) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type RoomJoinInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomJoinInput) Reset() {
	*x = RoomJoinInput{}
	mi := &file_internal_contracts_rooms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomJoinInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomJoinInput) ProtoMessage() {}

func (x *RoomJoinInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_rooms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomJoinInput.ProtoReflect.Descriptor instead.
func (*RoomJoinInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_rooms_proto_rawDescGZIP(), []int{2}
}

func (x *RoomJoinInput) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *RoomJoinInput) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type RoomJoinOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Joined        bool                   `protobuf:"varint,1,opt,name=joined,proto3" json:"joined,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomJoinOutput) Reset() {
	*x = RoomJoinOutput{}
	mi := &file_internal_contracts_rooms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomJoinOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomJoinOutput) ProtoMessage() {}

func (x *RoomJoinOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_rooms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomJoinOutput.ProtoReflect.Descriptor instead.
func (*RoomJoinOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_rooms_proto_rawDescGZIP(), []int{3}
}

func (x *RoomJoinOutput) GetJoined() bool {
	if x != nil {
		return x.Joined
	}
	return false
}

func (x *RoomJoinOutput) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *RoomJoinOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RoomLeaveConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomLeaveConfig) Reset() {
	*x = RoomLeaveConfig{}
	mi := &file_internal_contracts_rooms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomLeaveConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomLeaveConfig) ProtoMessage() {}

func (x *RoomLeaveConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_rooms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomLeaveConfig.ProtoReflect.Descriptor instead.
func (*RoomLeaveConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_rooms_proto_rawDescGZIP(), []int{4}
}

func (x *RoomLeaveConfig) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *RoomLeaveConfig) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type RoomLeaveInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomLeaveInput) Reset() {
	*x = RoomLeaveInput{}
	mi := &file_internal_contracts_rooms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomLeaveInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomLeaveInput) ProtoMessage() {}

func (x *RoomLeaveInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_rooms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomLeaveInput.ProtoReflect.Descriptor instead.
func (*RoomLeaveInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_rooms_proto_rawDescGZIP(), []int{5}
}

func (x *RoomLeaveInput) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *RoomLeaveInput) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type RoomLeaveOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          bool                   `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomLeaveOutput) Reset() {
	*x = RoomLeaveOutput{}
	mi := &file_internal_contracts_rooms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomLeaveOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomLeaveOutput) ProtoMessage() {}

func (x *RoomLeaveOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_rooms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomLeaveOutput.ProtoReflect.Descriptor instead.
func (*RoomLeaveOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_rooms_proto_rawDescGZIP(), []int{6}
}

func (x *RoomLeaveOutput) GetLeft() bool {
	if x != nil {
		return x.Left
	}
	return false
}

func (x *RoomLeaveOutput) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *RoomLeaveOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RoomBroadcastConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          string                 `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Exclude       string                 `protobuf:"bytes,3,opt,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomBroadcastConfig) Reset() {
	*x = RoomBroadcastConfig{}
	mi := &file_internal_contracts_rooms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomBroadcastConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomBroadcastConfig) ProtoMessage() {}

func (x *RoomBroadcastConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_rooms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomBroadcastConfig.ProtoReflect.Descriptor instead.
func (*RoomBroadcastConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_rooms_proto_rawDescGZIP(), []int{7}
}

func (x *RoomBroadcastConfig) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *RoomBroadcastConfig) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RoomBroadcastConfig) GetExclude() string {
	if x != nil {
		return x.Exclude
	}
	return ""
}

type RoomBroadcastInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          string                 `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Exclude       string                 `protobuf:"bytes,3,opt,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomBroadcastInput) Reset() {
	*x = RoomBroadcastInput{}
	mi := &file_internal_contracts_rooms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomBroadcastInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomBroadcastInput) ProtoMessage() {}

func (x *RoomBroadcastInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_rooms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomBroadcastInput.ProtoReflect.Descriptor instead.
func (*RoomBroadcastInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_rooms_proto_rawDescGZIP(), []int{8}
}

func (x *RoomBroadcastInput) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *RoomBroadcastInput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RoomBroadcastInput) GetExclude() string {
	if x != nil {
		return x.Exclude
	}
	return ""
}

type RoomBroadcastOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipients    int32                  `protobuf:"varint,1,opt,name=recipients,proto3" json:"recipients,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomBroadcastOutput) Reset() {
	*x = RoomBroadcastOutput{}
	mi := &file_internal_contracts_rooms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomBroadcastOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomBroadcastOutput) ProtoMessage() {}

func (x *RoomBroadcastOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_rooms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomBroadcastOutput.ProtoReflect.Descriptor instead.
func (*RoomBroadcastOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_rooms_proto_rawDescGZIP(), []int{9}
}

func (x *RoomBroadcastOutput) GetRecipients() int32 {
	if x != nil {
		return x.Recipients
	}
	return 0
}

func (x *RoomBroadcastOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RoomMembersConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          string                 `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomMembersConfig) Reset() {
	*x = RoomMembersConfig{}
	mi := &file_internal_contracts_rooms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMembersConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMembersConfig) ProtoMessage() {}

func (x *RoomMembersConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_rooms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMembersConfig.ProtoReflect.Descriptor instead.
func (*RoomMembersConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_rooms_proto_rawDescGZIP(), []int{10}
}

func (x *RoomMembersConfig) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type RoomMembersInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          string                 `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomMembersInput) Reset() {
	*x = RoomMembersInput{}
	mi := &file_internal_contracts_rooms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMembersInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMembersInput) ProtoMessage() {}

func (x *RoomMembersInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_rooms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMembersInput.ProtoReflect.Descriptor instead.
func (*RoomMembersInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_rooms_proto_rawDescGZIP(), []int{11}
}

func (x *RoomMembersInput) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type RoomMembersOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   []string               `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomMembersOutput) Reset() {
	*x = RoomMembersOutput{}
	mi := &file_internal_contracts_rooms_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMembersOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMembersOutput) ProtoMessage() {}

func (x *RoomMembersOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_rooms_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMembersOutput.ProtoReflect.Descriptor instead.
func (*RoomMembersOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_rooms_proto_rawDescGZIP(), []int{12}
}

func (x *RoomMembersOutput) GetConnections() []string {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *RoomMembersOutput) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RoomMembersOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_contracts_rooms_proto protoreflect.FileDescriptor

const file_internal_contracts_rooms_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/contracts/rooms.proto\x12\x19workflow.plugins.rooms.v1\"\x14\n" +
	"\x12RoomsManagerConfig\"I\n" +
	"\x0eRoomJoinConfig\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\"H\n" +
	"\rRoomJoinInput\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\"R\n" +
	"\x0eRoomJoinOutput\x12\x16\n" +
	"\x06joined\x18\x01 \x01(\bR\x06joined\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"J\n" +
	"\x0fRoomLeaveConfig\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\"I\n" +
	"\x0eRoomLeaveInput\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\"O\n" +
	"\x0fRoomLeaveOutput\x12\x12\n" +
	"\x04left\x18\x01 \x01(\bR\x04left\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"]\n" +
	"\x13RoomBroadcastConfig\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\aexclude\x18\x03 \x01(\tR\aexclude\"\\\n" +
	"\x12RoomBroadcastInput\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\aexclude\x18\x03 \x01(\tR\aexclude\"K\n" +
	"\x13RoomBroadcastOutput\x12\x1e\n" +
	"\n" +
	"recipients\x18\x01 \x01(\x05R\n" +
	"recipients\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"'\n" +
	"\x11RoomMembersConfig\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\"&\n" +
	"\x10RoomMembersInput\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\"a\n" +
	"\x11RoomMembersOutput\x12 \n" +
	"\vconnections\x18\x01 \x03(\tR\vconnections\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05errorBKZIgithub.com/GoCodeAlone/workflow-plugin-rooms/internal/contracts;contractsb\x06proto3"

var (
	file_internal_contracts_rooms_proto_rawDescOnce sync.Once
	file_internal_contracts_rooms_proto_rawDescData []byte
)

func file_internal_contracts_rooms_proto_rawDescGZIP() []byte {
	file_internal_contracts_rooms_proto_rawDescOnce.Do(func() {
		file_internal_contracts_rooms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_rooms_proto_rawDesc), len(file_internal_contracts_rooms_proto_rawDesc)))
	})
	return file_internal_contracts_rooms_proto_rawDescData
}

var file_internal_contracts_rooms_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_contracts_rooms_proto_goTypes = []any{
	(*RoomsManagerConfig)(nil),  // 0: workflow.plugins.rooms.v1.RoomsManagerConfig
	(*RoomJoinConfig)(nil),      // 1: workflow.plugins.rooms.v1.RoomJoinConfig
	(*RoomJoinInput)(nil),       // 2: workflow.plugins.rooms.v1.RoomJoinInput
	(*RoomJoinOutput)(nil),      // 3: workflow.plugins.rooms.v1.RoomJoinOutput
	(*RoomLeaveConfig)(nil),     // 4: workflow.plugins.rooms.v1.RoomLeaveConfig
	(*RoomLeaveInput)(nil),      // 5: workflow.plugins.rooms.v1.RoomLeaveInput
	(*RoomLeaveOutput)(nil),     // 6: workflow.plugins.rooms.v1.RoomLeaveOutput
	(*RoomBroadcastConfig)(nil), // 7: workflow.plugins.rooms.v1.RoomBroadcastConfig
	(*RoomBroadcastInput)(nil),  // 8: workflow.plugins.rooms.v1.RoomBroadcastInput
	(*RoomBroadcastOutput)(nil), // 9: workflow.plugins.rooms.v1.RoomBroadcastOutput
	(*RoomMembersConfig)(nil),   // 10: workflow.plugins.rooms.v1.RoomMembersConfig
	(*RoomMembersInput)(nil),    // 11: workflow.plugins.rooms.v1.RoomMembersInput
	(*RoomMembersOutput)(nil),   // 12: workflow.plugins.rooms.v1.RoomMembersOutput
}
var file_internal_contracts_rooms_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_contracts_rooms_proto_init() }
func file_internal_contracts_rooms_proto_init() {
	if File_internal_contracts_rooms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_rooms_proto_rawDesc), len(file_internal_contracts_rooms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_rooms_proto_goTypes,
		DependencyIndexes: file_internal_contracts_rooms_proto_depIdxs,
		MessageInfos:      file_internal_contracts_rooms_proto_msgTypes,
	}.Build()
	File_internal_contracts_rooms_proto = out.File
	file_internal_contracts_rooms_proto_goTypes = nil
	file_internal_contracts_rooms_proto_depIdxs = nil
}
